clean:
    mvn clean package

[working-directory: "data"]
fetchdata:
    wget "https://download.geofabrik.de/australia-oceania/new-zealand-latest.osm.pbf"
    osmium extract --bbox 174.45,-41.7,176.5,-40.7 new-zealand-latest.osm.pbf -o wellington.osm.pbf
    wget "https://wipfli.github.io/pgf-encoding/pgf-encoding.zip"
